name: Cowsay

on: push

jobs: 
  Ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        run: actions/checkout@v4

      - name: install cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute cowsay
        run: cowsay -f dragon "Run foe cover, i am a dragon" >> dragon.txt
    
      - name: test file exists
        run: grap -i "dragon" dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: checkout repo files
        run: ls

    
  