name: my first workflow

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print_msg
        run: echo "my first workflow"

      - name: list files
        run: ls
    
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: print_msg
        run: echo "my first workflow"

      - name: list files
        run: ls